### PR TITLE
Networkx 3.3 doesn't support Python 3.9 anymore

### PR DESCRIPTION
**Pull request by danielbrown2**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Networkx 3.3 dropped Python 3.9 https://github.com/networkx/networkx/pull/7028

The recipe for this feedstock hasn't been updated properly though: https://github.com/conda-forge/networkx-feedstock/blob/main/recipe/meta.yaml#L18

### CODE REVIEW

**Comment by h-vetinari** [comment]
FWIW, we need to fix the repodata anyway (because build `_0` would still remain "compatible" with 3.9, according to the metadata), see https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/697. This PR should still be merged because we need the updated lower bounds going forward.

**Comment by RMeli** [comment]
Thanks! I just bumped into this issue to.

**Comment by RMeli** [comment]
This has been an issue for the previous release as well, see https://github.com/conda-forge/networkx-feedstock/pull/52 and https://github.com/networkx/networkx/issues/7039. Is there a way to put some checks in place?

**Comment by h-vetinari** [comment]
> This has been an issue for the previous release as well, see #52 and [networkx/networkx#7039](https://github.com/networkx/networkx/issues/7039). Is there a way to put some checks in place?

Not easy to do with the current setup; we'd need to build it once and test it against several python versions, which conda-build doesn't support.

**Comment by h-vetinari** [comment]
It's basically up to the maintainers to be careful about this and check what upstream is doing, before pressing merge just because the CI is green.

**Comment by h-vetinari** [comment]
Now that https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/697 fixed this, let's put this in so we have a release-able state on `main` again.

**Comment by RMeli** [comment]
> which conda-build doesn't support

I see, thank you for the clarification.

**Comment by MridulS** [comment]
> It's basically up to the maintainers to be careful about this and check what upstream is doing, before pressing merge just because the CI is green.

Urghh my bad. Thanks for taking care of this everyone!!

**Comment by MridulS** [comment]
Also fwiw, I should also have updated the constrained deps.

**Pull request merged**
