### PR TITLE
Fix python and default dependencies lower bound

### PR DESCRIPTION
**Pull request by MridulS**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by MridulS** [comment]
@conda-forge-admin, please rerender

**Comment by MridulS** [comment]
Current conda-forge build of networkx is broken. We have had a lot of changes that depend on newer versions of python (like dataclasses) and this breaks builds for users using older versions of python.

**Comment by ocefpaf** [comment]
This is an example why we need grayskull regeneration ASAP! Pinging @marcelotrevisani for awareness.

Thanks @MridulS!

**Comment by MridulS** [comment]
Hey @ocefpaf! Could you add me as a maintainer for this feedstock?
I can make sure it's in line with our pypi releases :)

**Pull request merged**
